<a href="https://colab.research.google.com/github/jiachengpan/goldenspoon/blob/master/neverland_goldenspoon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
k_github_token = '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'
!rm -rf goldenspoon cached
!git clone https://$k_github_token@github.com/jiachengpan/goldenspoon.git

Cloning into 'goldenspoon'...
remote: Enumerating objects: 69, done.
remote: Counting objects: 100% (69/69), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 69 (delta 21), reused 52 (delta 10), pack-reused 0
Unpacking objects: 100% (69/69), done.

In [ ]:
import os
import sys
sys.path.append('goldenspoon')
import goldenspoon

In [ ]:
db = goldenspoon.Database('goldenspoon/data')

loading goldenspoon/data/stocks.basic_info.xls
loading goldenspoon/data/stocks.monthly_performance_2020.xls
loading goldenspoon/data/funds.total_value_and_stock_investment.xls
loading goldenspoon/data/stocks.margin_and_short_diff.xls
loading goldenspoon/data/stocks.monthly_performance_2021.xls
loading goldenspoon/data/funds.topn_stock_name.xls
loading goldenspoon/data/funds.basic_info.xls
loading goldenspoon/data/funds.topn_stock_mkt_value.xls
loading goldenspoon/data/funds.total_value_incr_ratio.xls
loading goldenspoon/data/funds.topn_stock_share_ratio.xls
loading goldenspoon/data/stocks.general.xls
loading goldenspoon/data/stocks.quarterly_report.xls
loading goldenspoon/data/stocks.topn_funds_holding.xls
WARN: column "持股基金家数 [股本类型]流通股本" value already assigned: key: ('688087.SH', datetime.date(2021, 6, 30)), value: 91.0 vs 92.0

# raw data

In [ ]:
db.get_funds().info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12554 entries, 0 to 12553
Data columns (total 14 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   基金代码                                    12554 non-null  object
 1   基金名称                                    12554 non-null  object
 2   任职基金数 [名次]第1名 [单位]只                     12551 non-null  float64
 3   任职天数 [名次]第1名 [单位]天                      12532 non-null  float64
 4   任职年化回报 [名次]第1名 [单位]%                    7959 non-null   float64
 5   任职期限最长的现任基金经理 [名次]第1名                   12551 non-null  object
 6   几何平均年化收益率 [名次]第1名 [收益率计算方法]普通收益率 [单位]%  12209 non-null  float64
 7   同类基金数量 [基金分类]二级分类 [单位]只                 12554 non-null  float64
 8   基金管理人简称                                 12554 non-null  object
 9   基金经理(历任)                                12554 non-null  object
 10  投资策略                                    12547 non-null  object
 11  投资类型(一级分类)                              12554 non-null  object
 12  投资类型(二级分类)                              12554 non-null  object
 13  规模同类排名 [基金分类]二级分类                       12295 non-null  object
dtypes: float64(5), object(9)
memory usage: 1.3+ MB

In [ ]:
db.get_fund_stats('date')

             基金代码  基金资产净值 [单位]元  ...          日期  股票投资市值 [单位]元
0       000001.OF  5.001782e+09  ...  2017-03-31  3.401957e+09
1       000001.OF  5.108970e+09  ...  2017-06-30  3.571111e+09
2       000001.OF  5.142564e+09  ...  2017-09-30  3.815853e+09
3       000001.OF  4.988448e+09  ...  2017-12-31  3.635405e+09
4       000001.OF  4.768081e+09  ...  2018-03-31  3.321465e+09
...           ...           ...  ...         ...           ...
125285  980003.OF  1.897466e+08  ...  2021-06-30           NaN
125286  000799.OF           NaN  ...  2019-12-31           NaN
125287  012810.OF           NaN  ...  2021-06-30           NaN
125288  012842.OF           NaN  ...  2021-06-30           NaN
125289  013273.OF           NaN  ...  2021-06-30           NaN

[125290 rows x 6 columns]

In [ ]:
db.get_fund_stats('topn_stocks')

           indicator         value       基金代码          日期  股票名称
0            重仓股股票市值  2.580000e+08  000001.OF  2017-03-31   五粮液
1        重仓股持仓占流通股比例  1.580713e-01  000001.OF  2017-03-31   五粮液
2            重仓股股票市值  2.277526e+08  000001.OF  2017-03-31  中国医药
3        重仓股持仓占流通股比例  9.518687e-01  000001.OF  2017-03-31  中国医药
4            重仓股股票市值  2.100000e+08  000001.OF  2017-03-31  神雾环保
...              ...           ...        ...         ...   ...
1587998  重仓股持仓占流通股比例  8.871600e-04  970021.OF  2021-06-30  新城控股
1587999      重仓股股票市值  5.856000e+05  970021.OF  2021-06-30  中国神华
1588000  重仓股持仓占流通股比例  1.819200e-04  970021.OF  2021-06-30  中国神华
1588001      重仓股股票市值  4.816000e+05  970021.OF  2021-06-30  保利地产
1588002  重仓股持仓占流通股比例  3.341800e-04  970021.OF  2021-06-30  保利地产

[1588003 rows x 5 columns]

In [ ]:
db.get_stocks().info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4473 entries, 0 to 4472
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   股票代码                      4473 non-null   object
 1   股票名称                      4473 non-null   object
 2   所属中信行业(2020) [行业类别]1级     4457 non-null   object
 3   所属中证行业(2016) [行业类别]1级     4469 non-null   object
 4   所属中证行业(2016) [行业类别]2级     4469 non-null   object
 5   所属中证行业(2016) [行业类别]3级     4469 non-null   object
 6   所属中证行业(2016) [行业类别]4级     4469 non-null   object
 7   所属国民经济行业 [行业级别]门类行业       4455 non-null   object
 8   所属申万行业(2021) [行业类别]1级     4457 non-null   object
 9   所属证监会行业(新) [行业级别]门类行业     4457 non-null   object
 10  是否属于重要指数成份 [所属指数]中小板指     4469 non-null   object
 11  是否属于重要指数成份 [所属指数]创业板指     4469 non-null   object
 12  是否属于重要指数成份 [所属指数]沪深300指数  4469 non-null   object
dtypes: object(13)
memory usage: 454.4+ KB

In [ ]:
db.get_stock_stats('date')

             股票代码  区间日均总市值 [起始交易日期]截止日3月前 [单位]亿元  ...  融资融券差额 [单位]亿元  融资融券差额 [单位]元
0       605198.SH                            NaN  ...            NaN           NaN
1       605198.SH                            NaN  ...            NaN           NaN
2       688501.SH                            NaN  ...            NaN           NaN
3       688501.SH                            NaN  ...            NaN           NaN
4       688067.SH                            NaN  ...            NaN           NaN
...           ...                            ...  ...            ...           ...
131284  603999.SH                            NaN  ...            NaN           NaN
131285  603999.SH                            NaN  ...            NaN           NaN
131286  688081.SH                            NaN  ...            NaN           NaN
131287  688181.SH                            NaN  ...            NaN           NaN
131288  688368.SH                            NaN  ...            NaN           NaN

[131289 rows x 18 columns]

# indicators

In [ ]:
import pandas as pd
import re
import datetime

class Indicator:
  def __init__(self, db):
    self.db = db

  k_column_date = '日期'

  k_stock_column_name           = '股票名称'
  k_stock_column_code           = '股票代码'
  k_stock_column_industry       = '所属中证行业(2016) [行业类别]{level}级'
  k_stock_column_type           = '股票风格分类'
  k_stock_column_total_value    = '区间日均总市值 [起始交易日期]截止日3月前 [单位]亿元'
  k_stock_column_avg_price      = '当月成交均价 [复权方式]不复权'
  k_stock_column_close_price    = '月收盘价 [复权方式]不复权'
  k_stock_column_turnover_rate  = '月换手率 [单位]%'
  k_stock_column_amplitutde     = '月振幅 [单位]%'
  k_stock_column_margin_diff    = '融资融券差额 [单位]元'
  k_stock_column_share_ratio_of_funds = '基金持股比例 [单位]% [比例类型]占流通股比例'
  k_stock_column_num_of_funds         = '持股基金家数 [股本类型]流通股本'

  def get_stocks(self):
    '''
    return: pd.DataFrame with columns: [股票名称, 股票代码]
    '''
    return self.db.get_stocks()[[self.k_stock_column_name, self.k_stock_column_code]].dropna()
  
  def get_stocks_map(self):
    '''
    return: dict: 股票代码 -> 股票名称
    '''
    return self.db.stock_map

  def get_stocks_name_map(self):
    '''
    return: dict: 股票名称 -> 股票代码
    '''
    return self.db.stock_map_reverse

  def add_stock_name(self, df):
    if self.k_stock_column_code in df:
      df[self.k_stock_column_name] = df[self.k_stock_column_code].map(self.get_stocks_map())
    elif self.k_stock_column_name in df:
      df[self.k_stock_column_code] = df[self.k_stock_column_name].map(self.get_stocks_name_map())
    else:
      assert 0, 'invalid df columns: {}'.format(df.columns.tolist())

    columns =  [self.k_column_date, self.k_stock_column_code, self.k_stock_column_name]
    columns += [col for col in df.columns if col not in columns]
    return df[[col for col in columns if col in df.columns]]

  def get_stock_general(self):
    '''
    return: pd.DataFrame with columns: [股票名称, 股票代码, 所属行业(四级), 类型]
    '''
    untimed_columns =  [self.k_stock_column_name, self.k_stock_column_code]
    untimed_columns += [self.k_stock_column_industry.format(level=i) for i in [1,2,3,4]]
    timed_columns   =  [self.k_column_date,
                        self.k_stock_column_code, 
                        self.k_stock_column_type]

    stocks_untimed = self.db.get_stocks()[untimed_columns]
    stocks_timed   = self.db.get_stock_stats('date')[timed_columns].dropna() \
                      .sort_values(self.k_column_date, ascending=False) \
                      .groupby([self.k_column_date, self.k_stock_column_code]) \
                      .last()
    return pd.merge(stocks_untimed, stocks_timed, on=self.k_stock_column_code).dropna()

  def get_stock_performance(self):
    columns = [self.k_column_date,
               self.k_stock_column_code,
               self.k_stock_column_close_price,
               self.k_stock_column_avg_price,
               self.k_stock_column_turnover_rate,
               self.k_stock_column_amplitutde,
               self.k_stock_column_margin_diff,
               ]
    stocks_timed = self.db.get_stock_stats('date')[columns].dropna()
    return self.add_stock_name(stocks_timed).dropna()

  def get_stock_holding_funds_share_ratio(self):
    columns = [self.k_column_date,
               self.k_stock_column_code,
               self.k_stock_column_share_ratio_of_funds,
               ]
    return self.add_stock_name(self.db.get_stock_stats('date')[columns].dropna()).dropna()

  def get_stock_holding_funds_number(self):
    columns = [self.k_column_date,
               self.k_stock_column_code,
               self.k_stock_column_num_of_funds,
               ]

    return self.add_stock_name(self.db.get_stock_stats('date')[columns].dropna()).dropna()

  def get_stock_topn_holding_funds(self):
    fund_topn_stocks = self.db.get_fund_stats('topn_stocks')
    fund_topn_stocks_share_ratio = fund_topn_stocks[fund_topn_stocks['indicator'] == '重仓股持仓占流通股比例'] \
                                    .groupby(self.k_stock_column_name)[self.k_fund_column_code] \
                                    .apply(set) \
                                    .reset_index()
    return self.add_stock_name(fund_topn_stocks_share_ratio.dropna()).dropna()
  

  k_fund_column_name  = '基金名称'
  k_fund_column_code  = '基金代码'
  k_fund_column_owner = '基金管理人简称'
  k_fund_column_type  = '投资类型(二级分类)'
  k_fund_column_total_value = '基金资产总值 [单位]元'
  k_fund_column_net_value   = '基金资产净值 [单位]元'
  k_fund_column_net_value_inc_rate  = '报告期净值增长率 [报告期净值数据项]过去3个月 [单位]%'
  #k_fund_column_income      = ''
  k_fund_column_manager             = '基金经理'
  k_fund_column_manager_longest     = '任职期限最长的现任基金经理 [名次]第1名'
  k_fund_column_manager_history     = '基金经理(历任)'

  def get_funds(self):
    return self.db.get_funds()[[self.k_fund_column_name, self.k_fund_column_code]].dropna()

  def get_funds_map(self):
    return self.db.fund_map

  def get_funds_name_map(self):
    return self.db.fund_map_reverse

  def get_funds_general(self):
    untimed_columns = [self.k_fund_column_name, 
                       self.k_fund_column_code, 
                       self.k_fund_column_owner,
                       self.k_fund_column_type,
                       ]
    timed_columns   = [self.k_column_date,
                       self.k_fund_column_code,
                       self.k_fund_column_total_value,
                       ]
    
    funds_untimed = self.db.get_funds()[untimed_columns]
    funds_timed   = self.db.get_fund_stats('date')[timed_columns].dropna() \
                      .sort_values(self.k_column_date, ascending=False) \
                      .groupby([self.k_column_date, self.k_fund_column_code]) \
                      .last()

    return pd.merge(funds_untimed, funds_timed, on=self.k_fund_column_code).dropna()

  def get_funds_manager(self):
    columns = [self.k_fund_column_code,
               self.k_fund_column_manager_history,
               ]
    re_manager = re.compile(r'(.+)\((\d.*)\)')
    date_fmt   = '%Y%m%d'

    result = []
    for fund_code, fund_managers in self.db.get_funds()[columns].values.tolist():
      for manager_str in fund_managers.split(','):
        m = re_manager.match(manager_str)
        assert m, 'invalid manager: {}'.format(manager_str)
        manager_name, manager_time = m.groups()

        if '-' in manager_time:
          start_time, end_time = manager_time.split('-')
          start_time = datetime.datetime.strptime(start_time, date_fmt)
          end_time   = datetime.datetime.strptime(end_time, date_fmt)
          current    = False
        elif '至今' in manager_time:
          start_time = datetime.datetime.strptime(manager_time[:8], date_fmt)
          end_time   = datetime.datetime.today()
          current    = True
        else:
          assert 0, 'invalid time {}'.format(manager_time)

        result.append({
            self.k_fund_column_code: fund_code,
            self.k_fund_column_manager: manager_name,
            'start': start_time,
            'end': end_time,
            'current': current,
        })

    return pd.DataFrame(result)

  def get_funds_manager_stats(self, only_current=True):
    df = self.get_funds_manager()

    if only_current:
      df = df[df['current'] == True]

    stats = df \
            .groupby(self.k_fund_column_manager)[self.k_fund_column_code] \
            .apply(set).reset_index()
    stats['基金名称'] = stats[self.k_fund_column_code].apply(lambda v: set([self.db.get_fund_by_code(vv) for vv in v]))
    stats['基金数量'] = stats[self.k_fund_column_code].apply(lambda v: len(v))

    return stats

  def get_funds_topn_stocks(self):
    fund_topn_stocks = self.db.get_fund_stats('topn_stocks')
    key_columns = [self.k_column_date,
                   self.k_fund_column_code, 
                   self.k_stock_column_name,
                   'indicator']
    fund_topn_stocks = fund_topn_stocks.groupby(key_columns).sum().reset_index()
    return fund_topn_stocks.pivot(index=[self.k_column_date,
                                         self.k_fund_column_code, 
                                         self.k_stock_column_name], 
                                  columns=['indicator'], 
                                  values=['value'])

## Stock Indicators

In [ ]:
ind = Indicator(db)

ind_stocks_general = ind.get_stock_general()
ind_stocks_perf    = ind.get_stock_performance()
ind_stocks_holding_funds_share_ratio = ind.get_stock_holding_funds_share_ratio()
ind_stocks_holding_funds_number = ind.get_stock_holding_funds_number()
ind_stocks_holding_topn_funds = ind.get_stock_topn_holding_funds()

In [ ]:
ind_stocks_general.shape

(4467, 7)

In [ ]:
ind_stocks_perf.head(10)

              日期       股票代码  股票名称  ...  月换手率 [单位]%  月振幅 [单位]%  融资融券差额 [单位]元
8916  2020-03-31  000001.SZ  平安银行  ...     13.6990    25.7241  3.028233e+09
8919  2020-06-30  000001.SZ  平安银行  ...      9.4140    10.4615  3.617990e+09
8922  2020-09-30  000001.SZ  平安银行  ...     11.0886     9.8806  2.541506e+09
8925  2020-12-31  000001.SZ  平安银行  ...     10.1084    13.7791  9.561380e+08
8928  2020-03-31  000002.SZ   万科A  ...     20.9200    28.7935  3.380240e+09
8931  2020-06-30  000002.SZ   万科A  ...     15.6810     9.7665  4.895297e+09
8934  2020-09-30  000002.SZ   万科A  ...     16.3117     9.6443  3.704119e+09
8937  2020-12-31  000002.SZ   万科A  ...     14.1500    14.3322  3.473595e+09
8964  2020-03-31  000006.SZ  深振业A  ...     25.2630    16.8467  5.073186e+08
8967  2020-06-30  000006.SZ  深振业A  ...     62.6600    42.4116  5.888608e+08

[10 rows x 8 columns]

In [ ]:
ind_stocks_holding_funds_share_ratio

                日期       股票代码  股票名称  基金持股比例 [单位]% [比例类型]占流通股比例
8916    2020-03-31  000001.SZ  平安银行                   2.755106
8919    2020-06-30  000001.SZ  平安银行                   3.628772
8922    2020-09-30  000001.SZ  平安银行                   3.277974
8925    2020-12-31  000001.SZ  平安银行                   5.983129
8928    2020-03-31  000002.SZ   万科A                   9.629097
...            ...        ...   ...                        ...
131281  2017-12-31  603999.SH  读者传媒                   0.042017
131282  2018-06-30  603999.SH  读者传媒                   0.015279
131283  2018-12-31  603999.SH  读者传媒                   0.006858
131284  2019-06-30  603999.SH  读者传媒                   0.043855
131285  2019-12-31  603999.SH  读者传媒                   0.014948

[49134 rows x 4 columns]

In [ ]:
ind_stocks_holding_funds_number

                日期       股票代码  股票名称  持股基金家数 [股本类型]流通股本
8916    2020-03-31  000001.SZ  平安银行              203.0
8919    2020-06-30  000001.SZ  平安银行              631.0
8922    2020-09-30  000001.SZ  平安银行              317.0
8925    2020-12-31  000001.SZ  平安银行             1095.0
8928    2020-03-31  000002.SZ   万科A              483.0
...            ...        ...   ...                ...
131284  2019-06-30  603999.SH  读者传媒                8.0
131285  2019-12-31  603999.SH  读者传媒                6.0
131286  2019-12-31  688081.SH  兴图新科                6.0
131287  2019-12-31  688181.SH  八亿时空                7.0
131288  2019-09-30  688368.SH  晶丰明源              144.0

[49219 rows x 4 columns]

In [ ]:
ind_stocks_holding_topn_funds

           股票代码   股票名称                                               基金代码
8     600306.SH  *ST商城       {519165.OF, 519157.OF, 519156.OF, 001294.OF}
10    002260.SZ  *ST德奥                                        {000471.OF}
11    300038.SZ  *ST数知                             {006733.OF, 050021.OF}
22    300795.SZ  *ST米奥                                        {003292.OF}
32    300076.SZ  GQY视讯                  {002236.OF, 004209.OF, 003359.OF}
...         ...    ...                                                ...
4257  300105.SZ   龙源技术                             {003704.OF, 006195.OF}
4259  688055.SH   龙腾光电                  {002810.OF, 004047.OF, 004046.OF}
4261  603906.SH   龙蟠科技  {310368.OF, 860016.OF, 860053.OF, 710302.OF, 0...
4262  688078.SH   龙软科技  {001430.OF, 673030.OF, 501027.SH, 004834.OF, 5...
4264  603686.SH   龙马环卫  {010257.OF, 004694.OF, 000409.OF, 530001.OF, 0...

[3403 rows x 3 columns]

## Fund Indicators

In [ ]:
ind = Indicator(db)
ind.get_funds_topn_stocks()

                                value
indicator                 重仓股持仓占流通股比例       重仓股股票市值
日期         基金代码      股票名称
2017-03-31 000001.OF 东方网络    1.442341  1.222859e+08
                     中国医药    0.951869  2.277526e+08
                     中工国际    0.727857  1.898110e+08
                     五粮液     0.158071  2.580000e+08
                     泸州老窖    0.142225  8.411285e+07
...                               ...           ...
2021-06-30 970021.OF 安迪苏     0.003542  1.136200e+06
                     新亚强     0.153767  2.720302e+06
                     新城控股    0.000887  8.320000e+05
                     格力电器    0.000503  1.563000e+06
                     立讯精密    0.000285  9.200000e+05

[794377 rows x 2 columns]

In [ ]:
ind = Indicator(db)
ind.get_funds_general()

                  基金名称       基金代码  ... 任职期限最长的现任基金经理 [名次]第1名  基金资产总值 [单位]元
0       融通新区域新经济灵活配置混合  001152.OF  ...                    关山  1.070679e+09
1       融通新区域新经济灵活配置混合  001152.OF  ...                    关山  9.992851e+08
2       融通新区域新经济灵活配置混合  001152.OF  ...                    关山  9.587891e+08
3       融通新区域新经济灵活配置混合  001152.OF  ...                    关山  8.557922e+08
4       融通新区域新经济灵活配置混合  001152.OF  ...                    关山  7.772274e+08
...                ...        ...  ...                   ...           ...
123691  太平洋证券六个月滚动持有债券  980003.OF  ...                    武媚  1.856550e+08
123692  太平洋证券六个月滚动持有债券  980003.OF  ...                    武媚  1.856161e+08
123693  太平洋证券六个月滚动持有债券  980003.OF  ...                    武媚  1.235115e+08
123694  太平洋证券六个月滚动持有债券  980003.OF  ...                    武媚  1.529985e+08
123695  太平洋证券六个月滚动持有债券  980003.OF  ...                    武媚  2.298303e+08

[123650 rows x 6 columns]

In [ ]:
funds = ind.db.get_funds()
funds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12554 entries, 0 to 12553
Data columns (total 14 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   基金代码                                    12554 non-null  object
 1   基金名称                                    12554 non-null  object
 2   任职基金数 [名次]第1名 [单位]只                     12551 non-null  float64
 3   任职天数 [名次]第1名 [单位]天                      12532 non-null  float64
 4   任职年化回报 [名次]第1名 [单位]%                    7959 non-null   float64
 5   任职期限最长的现任基金经理 [名次]第1名                   12551 non-null  object
 6   几何平均年化收益率 [名次]第1名 [收益率计算方法]普通收益率 [单位]%  12209 non-null  float64
 7   同类基金数量 [基金分类]二级分类 [单位]只                 12554 non-null  float64
 8   基金管理人简称                                 12554 non-null  object
 9   基金经理(历任)                                12554 non-null  object
 10  投资策略                                    12547 non-null  object
 11  投资类型(一级分类)                              12554 non-null  object
 12  投资类型(二级分类)                              12554 non-null  object
 13  规模同类排名 [基金分类]二级分类                       12295 non-null  object
dtypes: float64(5), object(9)
memory usage: 1.3+ MB

In [ ]:
funds.head()

        基金代码              基金名称  ...  投资类型(二级分类)  规模同类排名 [基金分类]二级分类
0  001152.OF    融通新区域新经济灵活配置混合  ...     灵活配置型基金          2293/5771
1  162703.SZ           广发小盘LOF  ...     偏股混合型基金            51/5771
2  340007.OF          兴全社会责任混合  ...     偏股混合型基金           163/5771
3  340008.OF          兴全有机增长混合  ...     灵活配置型基金           562/5771
4  007817.OF  国泰中证全指通信设备ETF联接A  ...     被动指数型基金          1206/2257

[5 rows x 14 columns]

In [ ]:
fund_stats = ind.db.get_fund_stats('date')
fund_stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125290 entries, 0 to 125289
Data columns (total 6 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   基金代码                            125290 non-null  object
 1   基金资产净值 [单位]元                    124260 non-null  float64
 2   基金资产总值 [单位]元                    123696 non-null  float64
 3   报告期净值增长率 [报告期净值数据项]过去3个月 [单位]%  119672 non-null  float64
 4   日期                              125290 non-null  object
 5   股票投资市值 [单位]元                    84725 non-null   float64
dtypes: float64(4), object(2)
memory usage: 5.7+ MB